<?xml version="1.0"?>
<!DOCTYPE root [
  <!ELEMENT root ANY>
  <!ELEMENT a (#PCDATA) >
  <!ELEMENT b (#PCDATA) >
  <!ELEMENT c (#PCDATA) >
  <!ELEMENT d (#PCDATA) >
  <!ELEMENT e (#PCDATA) >
  <!ELEMENT f (#PCDATA) >
  <!ELEMENT g (#PCDATA) >
  <!ELEMENT h (#PCDATA) >
  <!ELEMENT i (#PCDATA) >
  <!ELEMENT j (#PCDATA) >
  <!ELEMENT k (#PCDATA) >
  <!--* Tests all Attbuite types in P55,P56,P57,P58,P59 *-->
  <!ATTLIST a aattr1 ID #REQUIRED>
  <!ATTLIST b battr1 CDATA #REQUIRED 
              battr2 (good|bad) #REQUIRED 
              battr3 ID #REQUIRED>
  <!ATTLIST c c_reference IDREF #REQUIRED>
  <!ATTLIST d d_reference IDREFS #REQUIRED>
  <!ENTITY xmltech SYSTEM "xmltech.gif" NDATA gif>
  <!NOTATION gif SYSTEM "gif">
  <!ATTLIST e eattr1 ENTITY #REQUIRED>
  <!ENTITY IBMlogo SYSTEM "IBMlogo.gif" NDATA gif>
  <!ATTLIST f fattr1 ENTITIES #REQUIRED>
  <!ATTLIST g gattr1 NMTOKEN #REQUIRED>
  <!ATTLIST h hattr1 NMTOKENS #REQUIRED>
  <!NOTATION UTF-8 SYSTEM "UTF-8">
  <!ATTLIST i iattr1 NOTATION (UTF-8) #REQUIRED>
  <!--* Tests all DefaultDecl in P60 -->
  <!ATTLIST j jattr1 CDATA #REQUIRED 
              jattr2 CDATA "good" 
              jattr3 CDATA #FIXED "fixed"
	      jattr4 CDATA #IMPLIED >

]>
<root>
  <a aattr1 = "a1"> Element type a </a>
  <b battr1 = "anyvalue" battr2="good" battr3 ="b1"> Element type b </b>
  <c c_reference = "b1"> Element type c </c>
  <d d_reference = "a1 b1"> Element type d </d>
  <e eattr1 = "xmltech"> Element type e </e>
  <f fattr1 = "xmltech IBMlogo"> Element type f </f>
  <g gattr1 = "xml4j3_0_0_EA3"> Element type g </g>
  <h hattr1 = "xml4j3_0_0_EA3 Xerces-J_1_0_1"> Element type h </h>
  <i iattr1 = "UTF-8"> Element type i </i>
  <j jattr1 = "anyvalue" jattr2="good" jattr3 ="fixed"> Element type j </j>
</root>
<!--* a valid test: tests P54 *-->
